<?php

	WP SETTINGS SELECT FIELD CALLBACK 
		
	// callback: validate options
	function mpf_plugin_callback_validate_options( $input ) {

		/**
		 *
		 * Image Upload Validation
		 *
		 */

		$uploadedfile = $_FILES['jw_options_custom_image'];

		$upload_overrides = array( 'test_form' => false );

		$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );


		if ( $movefile && ! isset( $movefile['error'] ) ) {

		    $input['custom_image'] = $movefile['url'];

		    /**
		     *
		     * THIS BLOCK IS FOR MAKING UPLOADED IMAGE SHOW UP IN THE MEDIA LIB
		     *
		     */
		    

			$wp_upload_dir = wp_upload_dir();

			$attachment = array(
				"guid" => $movefile['file'], 
				"post_mime_type" => $movefile['type'],
				"post_title" => $uploadedfile['name'],
				"post_content" => "",
				"post_status" => "draft",
				"post_author" => 1
			);

			$id = wp_insert_attachment( $attachment, $movefile['file'],0);

			$attach_data = wp_generate_attachment_metadata( $id, $movefile['file'] );
			wp_update_attachment_metadata( $id, $attach_data );

		} else {
		    /**
		     * Error generated by _wp_handle_upload()
		     * @see _wp_handle_upload() in wp-admin/includes/file.php
		     */
   		    $options = get_option( 'jw_options' );
		    $input['custom_image'] = $options['custom_image'];

		}
		
		
		// custom url
		if ( isset( $input['custom_url'] ) ) {
			
			$input['custom_url'] = esc_url( $input['custom_url'] );
			
		}
		
		// custom title
		if ( isset( $input['custom_title'] ) ) {
			
			$input['custom_title'] = sanitize_text_field( $input['custom_title'] );
			
		}
		
		// custom style
		$radio_options = array(
			
			'enable'  => 'Enable custom styles',
			'disable' => 'Disable custom styles'
			
		);
		
		if ( ! isset( $input['custom_style'] ) ) {
			
			$input['custom_style'] = null;
			
		}
		if ( ! array_key_exists( $input['custom_style'], $radio_options ) ) {
			
			$input['custom_style'] = null;
			
		}
		
		// custom message
		if ( isset( $input['custom_message'] ) ) {
			
			$input['custom_message'] = wp_kses_post( $input['custom_message'] );
			
		}
		
		// custom footer
		if ( isset( $input['custom_footer'] ) ) {
			
			$input['custom_footer'] = sanitize_text_field( $input['custom_footer'] );
			
		}
		
		// custom toolbar
		if ( ! isset( $input['custom_toolbar'] ) ) {
			
			$input['custom_toolbar'] = null;
			
		}
		
		$input['custom_toolbar'] = ($input['custom_toolbar'] == 1 ? 1 : 0);
		
		// custom scheme
		$select_options = array(
			
			'default'   => 'Default',
			'light'     => 'Light',
			'blue'      => 'Blue',
			'coffee'    => 'Coffee',
			'ectoplasm' => 'Ectoplasm',
			'midnight'  => 'Midnight',
			'ocean'     => 'Ocean',
			'sunrise'   => 'Sunrise',
			
		);
		
		if ( ! isset( $input['custom_scheme'] ) ) {
			
			$input['custom_scheme'] = null;
			
		}
		
		if ( ! array_key_exists( $input['custom_scheme'], $select_options ) ) {
			
			$input['custom_scheme'] = null;
		
		}
		
		return $input;
		
	}



